[package]
name = "my_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "my_rust_lib"
crate-type = ["staticlib"]  # cdylib或者使用 "staticlib"，取决于你的需求
path="lib.rs"

[profile.release]
lto = true
opt-level = 3
debug = false
rpath = false